name: PR Closed Cleanup

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    uses: FranklinZuniorr/template-s3-cloudfront-ci/.github/workflows/clear_preview.yml@main
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}