name: Deploy to S3 and CloudFront

on:
  push:
    branches:
      - stage
  workflow_call: {}

jobs:
  deploy:
    uses: FranklinZuniorr/template-s3-cloudfront-ci/.github/workflows/push_release.yml@main
    environment:
      name: stage
    with:
      project_build_envs: ${{ vars.PROJECT_BUILD_ENVS }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
      WF_GITHUB_TOKEN: ${{ secrets.WF_GITHUB_TOKEN }}
